FROM docker.io/library/debian:bookworm-slim AS base

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    build-essential \
    devscripts \
    debhelper \
    dkms \
    dh-dkms \
    git \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /amneziawg-linux-kernel-module

CMD make build-deb
